// Generated by CoffeeScript 2.4.1
var Buffer;

Buffer = require('buffer').Buffer;

Buffer.prototype.writeZeroTerminatedString = function(str, offset, encoding) {
  var written;
  written = this.write(str, offset, encoding);
  this.writeUInt8(0, offset + written);
  return written + 1;
};

Buffer.prototype.readZeroTerminatedString = function(offset, encoding) {
  var endIndex;
  endIndex = offset;
  while (endIndex < this.length && this[endIndex] !== 0x00) {
    endIndex++;
  }
  return this.toString('ascii', offset, endIndex);
};

//######################################
// Debugging
//######################################

// Buffer.debug ?= (buffer) ->
//   bytes = ("#{byte}" for byte in buffer).join(", ")
//   "Buffer([#{bytes}])"
exports.Buffer = Buffer;
