// Generated by CoffeeScript 2.4.1
exports.VerticaError = class VerticaError extends Error {
  constructor(message) {
    super(message);
    this.message = message;
  }

};

exports.ConnectionError = class ConnectionError extends exports.VerticaError {};

exports.ConnectionErrorResponse = class ConnectionErrorResponse extends exports.ConnectionError {
  constructor(msg) {
    super(msg.information['Message']);
    this.fields = msg.information;
    this.code = msg.information['Code'];
  }

};

exports.AuthenticationError = class AuthenticationError extends exports.ConnectionErrorResponse {};

exports.SSLError = class SSLError extends exports.ConnectionError {};

exports.ClientStateError = class ClientStateError extends exports.VerticaError {};

exports.QueryError = class QueryError extends exports.VerticaError {};

exports.QueryErrorResponse = class QueryErrorResponse extends exports.QueryError {
  constructor(msg) {
    super(msg.information['Message']);
    this.fields = msg.information;
    this.code = msg.information['Code'];
  }

};
