// Generated by CoffeeScript 2.4.1
var Resultset;

Resultset = class Resultset {
  constructor(object) {
    this.fields = object.fields || [];
    this.rows = object.rows || [];
    this.notices = object.notices || [];
    this.status = object.status;
  }

  theValue() {
    return this.rows[0][0];
  }

  getLength() {
    return this.rows.length;
  }

  isEmpty() {
    return this.rows.length === 0;
  }

};

module.exports = Resultset;
